| Domain | Method   | URI                                   | Name                      | Action                                                                        | Middleware                                         |
+--------+----------+---------------------------------------+---------------------------+-------------------------------------------------------------------------------+----------------------------------------------------+
|        | GET|HEAD | owber                                 | owner.                    | Closure                                                                       | web                                                |
|        | GET|HEAD | owber/confirm-password                | owner.password.confirm    | App\Http\Controllers\Owner\Auth\ConfirmablePasswordController@show            | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\Authenticate:owners            |
|        | POST     | owber/confirm-password                | owner.                    | App\Http\Controllers\Owner\Auth\ConfirmablePasswordController@store           | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\Authenticate:owners            |
|        | GET|HEAD | owber/dashboard                       | owner.dashboard           | Closure                                                                       | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\Authenticate:owners            |
|        | POST     | owber/email/verification-notification | owner.verification.send   | App\Http\Controllers\Owner\Auth\EmailVerificationNotificationController@store | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\Authenticate:owners            |
|        |          |                                       |                           |                                                                               | Illuminate\Routing\Middleware\ThrottleRequests:6,1 |
|        | GET|HEAD | owber/forgot-password                 | owner.password.request    | App\Http\Controllers\Owner\Auth\PasswordResetLinkController@create            | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\RedirectIfAuthenticated        |
|        | POST     | owber/forgot-password                 | owner.password.email      | App\Http\Controllers\Owner\Auth\PasswordResetLinkController@store             | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\RedirectIfAuthenticated        |
|        | GET|HEAD | owber/login                           | owner.login               | App\Http\Controllers\Owner\Auth\AuthenticatedSessionController@create         | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\RedirectIfAuthenticated        |
|        | POST     | owber/login                           | owner.                    | App\Http\Controllers\Owner\Auth\AuthenticatedSessionController@store          | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\RedirectIfAuthenticated        |
|        | POST     | owber/logout                          | owner.logout              | App\Http\Controllers\Owner\Auth\AuthenticatedSessionController@destroy        | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\Authenticate:owners            |
|        | GET|HEAD | owber/register                        | owner.register            | App\Http\Controllers\Owner\Auth\RegisteredUserController@create               | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\RedirectIfAuthenticated        |
|        | POST     | owber/register                        | owner.                    | App\Http\Controllers\Owner\Auth\RegisteredUserController@store                | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\RedirectIfAuthenticated        |
|        | POST     | owber/reset-password                  | owner.password.update     | App\Http\Controllers\Owner\Auth\NewPasswordController@store                   | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\RedirectIfAuthenticated        |
|        | GET|HEAD | owber/reset-password/{token}          | owner.password.reset      | App\Http\Controllers\Owner\Auth\NewPasswordController@create                  | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\RedirectIfAuthenticated        |
|        | GET|HEAD | owber/verify-email                    | owner.verification.notice | App\Http\Controllers\Owner\Auth\EmailVerificationPromptController@__invoke    | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\Authenticate:owners            |
|        | GET|HEAD | owber/verify-email/{id}/{hash}        | owner.verification.verify | App\Http\Controllers\Owner\Auth\VerifyEmailController@__invoke                | web                                                |
|        |          |                                       |                           |                                                                               | App\Http\Middleware\Authenticate:owners            |
|        |          |       
